input {
  beats {
    port => 5044
    ssl => false
    client_inactivity_timeout => 60
    add_field => { "[@metadata][pipeline]" => "wazuh" }
  }
}

filter {
  if [@metadata][pipeline] == "wazuh" {
    if [data][integration] {
      # Already parsed JSON alerts from integrations
      json {
        source => "message"
        skip_on_invalid_json => true
      }
    }

    if [data][title] {
      # Wazuh alerts have a "data.title" field
      mutate {
        add_field => {
          "event_type" => "wazuh_alert"
          "alert_title" => "%{[data][title]}"
          "alert_level" => "%{[data][level]}"
        }
      }
    }

    # Add GeoIP if source IP exists
    if [data][srcip] {
      geoip {
        source => "[data][srcip]"
        target => "geoip"
      }
    }
  }
}

output {
  if [@metadata][pipeline] == "wazuh" {
    elasticsearch {
      hosts => ["${ELASTICSEARCH_HOSTS}"]
      user => "${ELASTICSEARCH_USERNAME}"
      password => "${ELASTICSEARCH_PASSWORD}"
      index => "wazuh-alerts-%{+YYYY.MM.dd}"
      ecs_compatibility => disabled
    }
  }
}